Search.appendIndex(
    [
                {
            "fqsen": "\\SmartDocs\\Admin",
            "name": "Admin",
            "summary": "Admin\u0020Class.",
            "url": "classes/SmartDocs-Admin.html"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/SmartDocs-Admin.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003Aregister_options_menu\u0028\u0029",
            "name": "register_options_menu",
            "summary": "Registers\u0020SmartDocs\u0020setting\u0020menu.",
            "url": "classes/SmartDocs-Admin.html#method_register_options_menu"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003Arender_settings_content\u0028\u0029",
            "name": "render_settings_content",
            "summary": "Renders\u0020content\u0020for\u0020the\u0020settings\u0020page.",
            "url": "classes/SmartDocs-Admin.html#method_render_settings_content"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003Aregister_plugin_settings\u0028\u0029",
            "name": "register_plugin_settings",
            "summary": "Registers\u0020plugin\u0020settings.",
            "url": "classes/SmartDocs-Admin.html#method_register_plugin_settings"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003Aadmin_enqueue_scripts\u0028\u0029",
            "name": "admin_enqueue_scripts",
            "summary": "Enqueue\u0020scripts\u0020on\u0020SmartDocs\u0020settings\u0020page.",
            "url": "classes/SmartDocs-Admin.html#method_admin_enqueue_scripts"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003Aadmin_bar_menu\u0028\u0029",
            "name": "admin_bar_menu",
            "summary": "Add\u0020Visit\u0020Documentation\u0020to\u0020Admin\u0020Bar\u0020Menu.",
            "url": "classes/SmartDocs-Admin.html#method_admin_bar_menu"
        },                {
            "fqsen": "\\SmartDocs\\Admin\u003A\u003Aremove_all_notices\u0028\u0029",
            "name": "remove_all_notices",
            "summary": "Remove\u0020all\u0020notices\u0020from\u0020the\u0020setting\u0020page.",
            "url": "classes/SmartDocs-Admin.html#method_remove_all_notices"
        },                {
            "fqsen": "\\SmartDocs\\Ajax",
            "name": "Ajax",
            "summary": "Ajax\u0020class.",
            "url": "classes/SmartDocs-Ajax.html"
        },                {
            "fqsen": "\\SmartDocs\\Ajax\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/SmartDocs-Ajax.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Ajax\u003A\u003Aon_settings_save\u0028\u0029",
            "name": "on_settings_save",
            "summary": "Fires\u0020on\u0020settings\u0020save\u0020event.",
            "url": "classes/SmartDocs-Ajax.html#method_on_settings_save"
        },                {
            "fqsen": "\\SmartDocs\\Ajax\u003A\u003Aget_search_results\u0028\u0029",
            "name": "get_search_results",
            "summary": "To\u0020render\u0020the\u0020search\u0020result.",
            "url": "classes/SmartDocs-Ajax.html#method_get_search_results"
        },                {
            "fqsen": "\\SmartDocs\\Ajax\u003A\u003Ahandle_doc_feedback\u0028\u0029",
            "name": "handle_doc_feedback",
            "summary": "Handle\u0020doc\u0020upvotes\u0020and\u0020downvotes.\u0020Save\u0020them\u0020in\u0020post\u0020meta.",
            "url": "classes/SmartDocs-Ajax.html#method_handle_doc_feedback"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader",
            "name": "Autoloader",
            "summary": "Autoloader\u0020class.",
            "url": "classes/SmartDocs-Autoloader.html"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020autoloader.",
            "url": "classes/SmartDocs-Autoloader.html#method_run"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader\u003A\u003Aget_classes_map\u0028\u0029",
            "name": "get_classes_map",
            "summary": "Get\u0020classes\u0020map\u0020with\u0020file\u0020names.",
            "url": "classes/SmartDocs-Autoloader.html#method_get_classes_map"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader\u003A\u003Ainit_classes_map\u0028\u0029",
            "name": "init_classes_map",
            "summary": "Initializes\u0020classes\u0020map\u0020with\u0020file\u0020names.",
            "url": "classes/SmartDocs-Autoloader.html#method_init_classes_map"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader\u003A\u003Aload_class\u0028\u0029",
            "name": "load_class",
            "summary": "Load\u0020class.",
            "url": "classes/SmartDocs-Autoloader.html#method_load_class"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader\u003A\u003Aautoload\u0028\u0029",
            "name": "autoload",
            "summary": "Autoload.",
            "url": "classes/SmartDocs-Autoloader.html#method_autoload"
        },                {
            "fqsen": "\\SmartDocs\\Autoloader\u003A\u003A\u0024classes_map",
            "name": "classes_map",
            "summary": "Classes\u0020map.",
            "url": "classes/SmartDocs-Autoloader.html#property_classes_map"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb",
            "name": "Breadcrumb",
            "summary": "Breadcrumb\u0020class.",
            "url": "classes/SmartDocs-Breadcrumb.html"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Aadd_crumb\u0028\u0029",
            "name": "add_crumb",
            "summary": "Add\u0020a\u0020crumb\u0020so\u0020we\u0020don\u0027t\u0020get\u0020lost.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_add_crumb"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Reset\u0020crumbs.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_reset"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Aget_breadcrumb\u0028\u0029",
            "name": "get_breadcrumb",
            "summary": "Get\u0020the\u0020breadcrumb.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_get_breadcrumb"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generate\u0020breadcrumb\u0020trail.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_generate"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Aprepend_docs_page\u0028\u0029",
            "name": "prepend_docs_page",
            "summary": "Prepend\u0020the\u0020docs\u0020page\u0020to\u0020docs\u0020breadcrumbs.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_prepend_docs_page"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Aadd_crumbs_smartdocs_single\u0028\u0029",
            "name": "add_crumbs_smartdocs_single",
            "summary": "Single\u0020post\u0020trail.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_add_crumbs_smartdocs_single"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Aadd_crumbs_smartdocs_category\u0028\u0029",
            "name": "add_crumbs_smartdocs_category",
            "summary": "Docs\u0020category\u0020trail.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_add_crumbs_smartdocs_category"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Aterm_ancestors\u0028\u0029",
            "name": "term_ancestors",
            "summary": "Add\u0020crumbs\u0020for\u0020a\u0020term.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_term_ancestors"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003Apaged_trail\u0028\u0029",
            "name": "paged_trail",
            "summary": "Add\u0020a\u0020breadcrumb\u0020for\u0020pagination.",
            "url": "classes/SmartDocs-Breadcrumb.html#method_paged_trail"
        },                {
            "fqsen": "\\SmartDocs\\Breadcrumb\u003A\u003A\u0024crumbs",
            "name": "crumbs",
            "summary": "Breadcrumb\u0020trail.",
            "url": "classes/SmartDocs-Breadcrumb.html#property_crumbs"
        },                {
            "fqsen": "\\SmartDocs\\Cpt",
            "name": "Cpt",
            "summary": "Cpt\u0020class.",
            "url": "classes/SmartDocs-Cpt.html"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/SmartDocs-Cpt.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Aregister_cpt\u0028\u0029",
            "name": "register_cpt",
            "summary": "Register\u0020custom\u0020post\u0020type\u0020and\u0020taxonomies.",
            "url": "classes/SmartDocs-Cpt.html#method_register_cpt"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Afix_rewrite_rules\u0028\u0029",
            "name": "fix_rewrite_rules",
            "summary": "SmartDocs\u0020rewrite\u0020rule\u0020fixes.",
            "url": "classes/SmartDocs-Cpt.html#method_fix_rewrite_rules"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Afilter_post_type_link\u0028\u0029",
            "name": "filter_post_type_link",
            "summary": "Filter\u0020to\u0020allow\u0020smartdocs_category\u0020in\u0020the\u0020permalinks\u0020for\u0020products.",
            "url": "classes/SmartDocs-Cpt.html#method_filter_post_type_link"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Aget_post_type_icon\u0028\u0029",
            "name": "get_post_type_icon",
            "summary": "Base64\u0020encoded\u0020svg\u0020icon.",
            "url": "classes/SmartDocs-Cpt.html#method_get_post_type_icon"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Acpt_columns\u0028\u0029",
            "name": "cpt_columns",
            "summary": "CPT\u0020Columns",
            "url": "classes/SmartDocs-Cpt.html#method_cpt_columns"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Acpt_columns_data\u0028\u0029",
            "name": "cpt_columns_data",
            "summary": "CPT\u0020Columns\u0020data",
            "url": "classes/SmartDocs-Cpt.html#method_cpt_columns_data"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Aget_cpt_rewrite_slug\u0028\u0029",
            "name": "get_cpt_rewrite_slug",
            "summary": "Get\u0020CPT\u0020rewrite\u0020slug.",
            "url": "classes/SmartDocs-Cpt.html#method_get_cpt_rewrite_slug"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Aget_category_rewrite_slug\u0028\u0029",
            "name": "get_category_rewrite_slug",
            "summary": "Get\u0020category\u0020rewrite\u0020slug.",
            "url": "classes/SmartDocs-Cpt.html#method_get_category_rewrite_slug"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Aprint_admin_menu_style\u0028\u0029",
            "name": "print_admin_menu_style",
            "summary": "Print\u0020admin\u0020menu\u0020style.",
            "url": "classes/SmartDocs-Cpt.html#method_print_admin_menu_style"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Ataxonomy_admin_scripts\u0028\u0029",
            "name": "taxonomy_admin_scripts",
            "summary": "Taxonomy\u0020admin\u0020scripts.",
            "url": "classes/SmartDocs-Cpt.html#method_taxonomy_admin_scripts"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Ataxonomy_admin_styles\u0028\u0029",
            "name": "taxonomy_admin_styles",
            "summary": "Taxonomy\u0020admin\u0020styles.",
            "url": "classes/SmartDocs-Cpt.html#method_taxonomy_admin_styles"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Aenable_category_thumbnail\u0028\u0029",
            "name": "enable_category_thumbnail",
            "summary": "Enable\u0020category\u0020thumbnail.",
            "url": "classes/SmartDocs-Cpt.html#method_enable_category_thumbnail"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Ataxonomy_thumbnail_save_term\u0028\u0029",
            "name": "taxonomy_thumbnail_save_term",
            "summary": "Save\u0020Edited\u0020Term.",
            "url": "classes/SmartDocs-Cpt.html#method_taxonomy_thumbnail_save_term"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Amanage_taxonomy_columns\u0028\u0029",
            "name": "manage_taxonomy_columns",
            "summary": "Edit\u0020Term\u0020Columns.",
            "url": "classes/SmartDocs-Cpt.html#method_manage_taxonomy_columns"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Amanage_taxonomy_custom_column\u0028\u0029",
            "name": "manage_taxonomy_custom_column",
            "summary": "Edit\u0020Term\u0020Rows.",
            "url": "classes/SmartDocs-Cpt.html#method_manage_taxonomy_custom_column"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Ataxonomy_thumbnail_edit_tag_form\u0028\u0029",
            "name": "taxonomy_thumbnail_edit_tag_form",
            "summary": "Edit\u0020Term\u0020Control.",
            "url": "classes/SmartDocs-Cpt.html#method_taxonomy_thumbnail_edit_tag_form"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003Ataxonomy_thumbnail_add_tag_form\u0028\u0029",
            "name": "taxonomy_thumbnail_add_tag_form",
            "summary": "Add\u0020Term\u0020Control.",
            "url": "classes/SmartDocs-Cpt.html#method_taxonomy_thumbnail_add_tag_form"
        },                {
            "fqsen": "\\SmartDocs\\Cpt\u003A\u003A\u0024post_type",
            "name": "post_type",
            "summary": "Docs\u0020post\u0020type.",
            "url": "classes/SmartDocs-Cpt.html#property_post_type"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control",
            "name": "Customizer_Control",
            "summary": "Custom\u0020Customizer\u0020controls.",
            "url": "classes/SmartDocs-Customizer-Control.html"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/SmartDocs-Customizer-Control.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Renders\u0020the\u0020control\u0020wrapper\u0020and\u0020calls\u0020\u0024this\u002D\u003Erender_content\u0028\u0029\u0020for\u0020the\u0020internals.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_content\u0028\u0029",
            "name": "render_content",
            "summary": "Renders\u0020the\u0020content\u0020for\u0020a\u0020control\u0020based\u0020on\u0020the\u0020type\nof\u0020control\u0020specified\u0020when\u0020this\u0020class\u0020is\u0020initialized.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_content"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_content_title\u0028\u0029",
            "name": "render_content_title",
            "summary": "Renders\u0020the\u0020title\u0020and\u0020description\u0020for\u0020a\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_content_title"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_connect_attribute\u0028\u0029",
            "name": "render_connect_attribute",
            "summary": "Renders\u0020the\u0020connect\u0020attribute\u0020for\u0020a\u0020connected\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_connect_attribute"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_line\u0028\u0029",
            "name": "render_line",
            "summary": "Renders\u0020a\u0020line\u0020break\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_line"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_slider\u0028\u0029",
            "name": "render_slider",
            "summary": "Renders\u0020the\u0020slider\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_slider"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_responsive_slider\u0028\u0029",
            "name": "render_responsive_slider",
            "summary": "Renders\u0020the\u0020slider\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_responsive_slider"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_dimension\u0028\u0029",
            "name": "render_dimension",
            "summary": "Renders\u0020the\u0020dimension\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_dimension"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_color_picker\u0028\u0029",
            "name": "render_color_picker",
            "summary": "Renders\u0020the\u0020color\u0020picker\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_color_picker"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_section\u0028\u0029",
            "name": "render_section",
            "summary": "Renders\u0020the\u0020section\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_section"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_sub_section\u0028\u0029",
            "name": "render_sub_section",
            "summary": "Renders\u0020the\u0020sub\u002Dsection\u0020control.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_sub_section"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003Arender_responsive_control\u0028\u0029",
            "name": "render_responsive_control",
            "summary": "Renders\u0020the\u0020responsive\u0020control\u0020and\u0020settings.",
            "url": "classes/SmartDocs-Customizer-Control.html#method_render_responsive_control"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003A\u0024connect",
            "name": "connect",
            "summary": "Used\u0020to\u0020connect\u0020controls\u0020to\u0020each\u0020other.",
            "url": "classes/SmartDocs-Customizer-Control.html#property_connect"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003A\u0024preview_button",
            "name": "preview_button",
            "summary": "If\u0020true,\u0020the\u0020preview\u0020button\u0020for\u0020a\u0020control\u0020will\u0020be\u0020rendered.",
            "url": "classes/SmartDocs-Customizer-Control.html#property_preview_button"
        },                {
            "fqsen": "\\SmartDocs\\Customizer_Control\u003A\u003A\u0024args",
            "name": "args",
            "summary": "Reference\u0020to\u0020the\u0020class\u0020\u0060\u0024args\u0060\u0020parameter.",
            "url": "classes/SmartDocs-Customizer-Control.html#property_args"
        },                {
            "fqsen": "\\SmartDocs\\Customizer",
            "name": "Customizer",
            "summary": "Customizer\u0020Class.",
            "url": "classes/SmartDocs-Customizer.html"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/SmartDocs-Customizer.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Aadd_sections\u0028\u0029",
            "name": "add_sections",
            "summary": "Add\u0020panels\u0020and\u0020sections\u0020into\u0020Customizer.",
            "url": "classes/SmartDocs-Customizer.html#method_add_sections"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Aenqueue_customizer_preview_script\u0028\u0029",
            "name": "enqueue_customizer_preview_script",
            "summary": "Enqueue\u0020customizer\u0020preview\u0020scripts.",
            "url": "classes/SmartDocs-Customizer.html#method_enqueue_customizer_preview_script"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Aenqueue_customizer_controls\u0028\u0029",
            "name": "enqueue_customizer_controls",
            "summary": "Enqueue\u0020customizer\u0020controls\u0020scripts.",
            "url": "classes/SmartDocs-Customizer.html#method_enqueue_customizer_controls"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Ais_customizer_preview\u0028\u0029",
            "name": "is_customizer_preview",
            "summary": "Checks\u0020to\u0020see\u0020if\u0020this\u0020is\u0020a\u0020Customizer\u0020preview\u0020or\u0020not.",
            "url": "classes/SmartDocs-Customizer.html#method_is_customizer_preview"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Abox_shadow_css\u0028\u0029",
            "name": "box_shadow_css",
            "summary": "Helper\u0020function\u0020to\u0020generate\u0020box\u002Dshadow\u0020CSS.",
            "url": "classes/SmartDocs-Customizer.html#method_box_shadow_css"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Asanitize_number\u0028\u0029",
            "name": "sanitize_number",
            "summary": "Sanitize\u0020callback\u0020for\u0020Customizer\u0020number\u0020field.",
            "url": "classes/SmartDocs-Customizer.html#method_sanitize_number"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Asanitize_integer\u0028\u0029",
            "name": "sanitize_integer",
            "summary": "Sanitize\u0020callback\u0020for\u0020integer\u0020value.",
            "url": "classes/SmartDocs-Customizer.html#method_sanitize_integer"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Ahex2rgba\u0028\u0029",
            "name": "hex2rgba",
            "summary": "Converts\u0020hex\u0020color\u0020to\u0020rgba.",
            "url": "classes/SmartDocs-Customizer.html#method_hex2rgba"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Async_customizer_breakpoints\u0028\u0029",
            "name": "sync_customizer_breakpoints",
            "summary": "Sync\u0020Customizer\u0020responsive\u0020preview\u0020dimensions\u0020with\ncustom\u0020breakpoints.",
            "url": "classes/SmartDocs-Customizer.html#method_sync_customizer_breakpoints"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003Aperform_template_actions\u0028\u0029",
            "name": "perform_template_actions",
            "summary": "Add\u0020or\u0020remove\u0020elements\u0020based\u0020on\u0020Customizer\u0020setting.",
            "url": "classes/SmartDocs-Customizer.html#method_perform_template_actions"
        },                {
            "fqsen": "\\SmartDocs\\Customizer\u003A\u003A\u0024_is_preview",
            "name": "_is_preview",
            "summary": "A\u0020flag\u0020to\u0020check\u0020whether\u0020we\u0027re\u0020in\u0020a\u0020Customizer\npreview\u0020or\u0020not.",
            "url": "classes/SmartDocs-Customizer.html#property__is_preview"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS",
            "name": "Dynamic_CSS",
            "summary": "Dynamic\u0020CSS\u0020Class.",
            "url": "classes/SmartDocs-Dynamic-CSS.html"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003Aget_mod\u0028\u0029",
            "name": "get_mod",
            "summary": "Get\u0020value\u0020from\u0020the\u0020Customizer.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method_get_mod"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003Aadd_rule\u0028\u0029",
            "name": "add_rule",
            "summary": "Add\u0020CSS\u0020rule.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method_add_rule"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003Abuild_hero_section_style\u0028\u0029",
            "name": "build_hero_section_style",
            "summary": "Build\u0020style\u0020for\u0020Hero\u0020section.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method_build_hero_section_style"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003Abuild_categories_grid_style\u0028\u0029",
            "name": "build_categories_grid_style",
            "summary": "Build\u0020style\u0020for\u0020categories\u0020grid.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method_build_categories_grid_style"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003Abuild_responsive_styles\u0028\u0029",
            "name": "build_responsive_styles",
            "summary": "Build\u0020responsive\u0020styles.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method_build_responsive_styles"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003Arender_styles\u0028\u0029",
            "name": "render_styles",
            "summary": "Iterate\u0020through\u0020built\u0020styles\u0020and\u0020render\u0020with\u0020media\u0020queries.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#method_render_styles"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003A\u0024breakpoints",
            "name": "breakpoints",
            "summary": "Holds\u0020breakpoints.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#property_breakpoints"
        },                {
            "fqsen": "\\SmartDocs\\Dynamic_CSS\u003A\u003A\u0024styles",
            "name": "styles",
            "summary": "Holds\u0020CSS\u0020rules.",
            "url": "classes/SmartDocs-Dynamic-CSS.html#property_styles"
        },                {
            "fqsen": "\\SmartDocs\\Plugin",
            "name": "Plugin",
            "summary": "SmartDocs\u0020Plugin.",
            "url": "classes/SmartDocs-Plugin.html"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "Clone.",
            "url": "classes/SmartDocs-Plugin.html#method___clone"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A__wakeup\u0028\u0029",
            "name": "__wakeup",
            "summary": "Wakeup.",
            "url": "classes/SmartDocs-Plugin.html#method___wakeup"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Plugin\u0020constructor.",
            "url": "classes/SmartDocs-Plugin.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Init.",
            "url": "classes/SmartDocs-Plugin.html#method_init"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Aadmin_init\u0028\u0029",
            "name": "admin_init",
            "summary": "Admin\u0020Init.",
            "url": "classes/SmartDocs-Plugin.html#method_admin_init"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Ainit_components\u0028\u0029",
            "name": "init_components",
            "summary": "Init\u0020components.",
            "url": "classes/SmartDocs-Plugin.html#method_init_components"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Aregister_autoloader\u0028\u0029",
            "name": "register_autoloader",
            "summary": "Register\u0020autoloader.",
            "url": "classes/SmartDocs-Plugin.html#method_register_autoloader"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Aplugin_activation\u0028\u0029",
            "name": "plugin_activation",
            "summary": "Plugin\u0020Activation.",
            "url": "classes/SmartDocs-Plugin.html#method_plugin_activation"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Aplugin_deactivation\u0028\u0029",
            "name": "plugin_deactivation",
            "summary": "Plugin\u0020Deactivation.",
            "url": "classes/SmartDocs-Plugin.html#method_plugin_deactivation"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Aenqueue_scripts\u0028\u0029",
            "name": "enqueue_scripts",
            "summary": "Enqueue\u0020scripts.",
            "url": "classes/SmartDocs-Plugin.html#method_enqueue_scripts"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003Ahandle_customizer_styles\u0028\u0029",
            "name": "handle_customizer_styles",
            "summary": "Handle\u0020Customizer\u0020Styles.",
            "url": "classes/SmartDocs-Plugin.html#method_handle_customizer_styles"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_instance"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024cpt",
            "name": "cpt",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_cpt"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024admin",
            "name": "admin",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_admin"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024shortcode",
            "name": "shortcode",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_shortcode"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024template",
            "name": "template",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_template"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024ajax",
            "name": "ajax",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_ajax"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024widget",
            "name": "widget",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_widget"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024structured_data",
            "name": "structured_data",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_structured_data"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024customizer",
            "name": "customizer",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_customizer"
        },                {
            "fqsen": "\\SmartDocs\\Plugin\u003A\u003A\u0024dynamic_css",
            "name": "dynamic_css",
            "summary": "Instance.",
            "url": "classes/SmartDocs-Plugin.html#property_dynamic_css"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data",
            "name": "Structured_Data",
            "summary": "Structure\u0020data\u0020class.",
            "url": "classes/SmartDocs-Structured-Data.html"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/SmartDocs-Structured-Data.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Aset_data\u0028\u0029",
            "name": "set_data",
            "summary": "Sets\u0020data.",
            "url": "classes/SmartDocs-Structured-Data.html#method_set_data"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Aget_data\u0028\u0029",
            "name": "get_data",
            "summary": "Gets\u0020data.",
            "url": "classes/SmartDocs-Structured-Data.html#method_get_data"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Aget_structured_data\u0028\u0029",
            "name": "get_structured_data",
            "summary": "Structures\u0020and\u0020returns\u0020data.",
            "url": "classes/SmartDocs-Structured-Data.html#method_get_structured_data"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Aget_data_type_for_page\u0028\u0029",
            "name": "get_data_type_for_page",
            "summary": "Get\u0020data\u0020types\u0020for\u0020pages.",
            "url": "classes/SmartDocs-Structured-Data.html#method_get_data_type_for_page"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Aoutput_structured_data\u0028\u0029",
            "name": "output_structured_data",
            "summary": "Sanitizes,\u0020encodes\u0020and\u0020outputs\u0020structured\u0020data.",
            "url": "classes/SmartDocs-Structured-Data.html#method_output_structured_data"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Aesc_json\u0028\u0029",
            "name": "esc_json",
            "summary": "Escape\u0020JSON\u0020for\u0020use\u0020on\u0020HTML\u0020or\u0020attribute\u0020text\u0020nodes.",
            "url": "classes/SmartDocs-Structured-Data.html#method_esc_json"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003Agenerate_breadcrumblist_data\u0028\u0029",
            "name": "generate_breadcrumblist_data",
            "summary": "Generates\u0020BreadcrumbList\u0020structured\u0020data.",
            "url": "classes/SmartDocs-Structured-Data.html#method_generate_breadcrumblist_data"
        },                {
            "fqsen": "\\SmartDocs\\Structured_Data\u003A\u003A\u0024_data",
            "name": "_data",
            "summary": "Stores\u0020the\u0020structured\u0020data.",
            "url": "classes/SmartDocs-Structured-Data.html#property__data"
        },                {
            "fqsen": "\\SmartDocs\\Template",
            "name": "Template",
            "summary": "Template\u0020class.",
            "url": "classes/SmartDocs-Template.html"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/SmartDocs-Template.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003Atemplate_loader\u0028\u0029",
            "name": "template_loader",
            "summary": "Load\u0020SmartDocs\u0020template\u0020for\u0020CPT.",
            "url": "classes/SmartDocs-Template.html#method_template_loader"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003Aget_template_path\u0028\u0029",
            "name": "get_template_path",
            "summary": "Retrieves\u0020the\u0020path\u0020of\u0020the\u0020template\u0020file.",
            "url": "classes/SmartDocs-Template.html#method_get_template_path"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003Agenerator_meta_tag\u0028\u0029",
            "name": "generator_meta_tag",
            "summary": "Output\u0020generator\u0020tag\u0020to\u0020aid\u0020debugging.",
            "url": "classes/SmartDocs-Template.html#method_generator_meta_tag"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003Abody_class\u0028\u0029",
            "name": "body_class",
            "summary": "Add\u0020body\u0020classes\u0020for\u0020SmartDocs\u0020pages.",
            "url": "classes/SmartDocs-Template.html#method_body_class"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003Atheme_compats\u0028\u0029",
            "name": "theme_compats",
            "summary": "Theme\u0020compatibilities.",
            "url": "classes/SmartDocs-Template.html#method_theme_compats"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003A\u0024post_type",
            "name": "post_type",
            "summary": "SmartDocs\u0020CPT\u0020Name.",
            "url": "classes/SmartDocs-Template.html#property_post_type"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003A\u0024override_single",
            "name": "override_single",
            "summary": "Override\u0020single.",
            "url": "classes/SmartDocs-Template.html#property_override_single"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003A\u0024override_tax_archive",
            "name": "override_tax_archive",
            "summary": "Override\u0020taxonomy\u0020archive.",
            "url": "classes/SmartDocs-Template.html#property_override_tax_archive"
        },                {
            "fqsen": "\\SmartDocs\\Template\u003A\u003A\u0024has_docs_template",
            "name": "has_docs_template",
            "summary": "Has\u0020docs\u0020template.",
            "url": "classes/SmartDocs-Template.html#property_has_docs_template"
        },                {
            "fqsen": "\\SmartDocs\\Widget",
            "name": "Widget",
            "summary": "Widget\u0020class.",
            "url": "classes/SmartDocs-Widget.html"
        },                {
            "fqsen": "\\SmartDocs\\Widget\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020calling\u0020the\u0020docs\u0020widgets",
            "url": "classes/SmartDocs-Widget.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Widget\u003A\u003Aregister_sidebar\u0028\u0029",
            "name": "register_sidebar",
            "summary": "Register\u0020sidebar\u0020for\u0020widget\u0020area.",
            "url": "classes/SmartDocs-Widget.html#method_register_sidebar"
        },                {
            "fqsen": "\\SmartDocs\\Widget\u003A\u003Aregister_wp_widgets\u0028\u0029",
            "name": "register_wp_widgets",
            "summary": "Register\u0020widgets.",
            "url": "classes/SmartDocs-Widget.html#method_register_wp_widgets"
        },                {
            "fqsen": "\\SmartDocs\\Widgets\\Category_Widget",
            "name": "Category_Widget",
            "summary": "Category_Widget\u0020class\u0020extending\u0020WP_Widget\u0020class.",
            "url": "classes/SmartDocs-Widgets-Category-Widget.html"
        },                {
            "fqsen": "\\SmartDocs\\Widgets\\Category_Widget\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/SmartDocs-Widgets-Category-Widget.html#method___construct"
        },                {
            "fqsen": "\\SmartDocs\\Widgets\\Category_Widget\u003A\u003Awidget\u0028\u0029",
            "name": "widget",
            "summary": "Overriding\u0020widget\u0020method\u0020of\u0020the\u0020parent.",
            "url": "classes/SmartDocs-Widgets-Category-Widget.html#method_widget"
        },                {
            "fqsen": "\\SmartDocs\\Widgets\\Category_Widget\u003A\u003Aform\u0028\u0029",
            "name": "form",
            "summary": "Overriding\u0020form\u0020function\u0020of\u0020the\u0020parent.",
            "url": "classes/SmartDocs-Widgets-Category-Widget.html#method_form"
        },                {
            "fqsen": "\\SmartDocs\\Widgets\\Category_Widget\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Overriding\u0020update\u0020function\u0020of\u0020the\u0020parent.",
            "url": "classes/SmartDocs-Widgets-Category-Widget.html#method_update"
        },                {
            "fqsen": "\\smartdocs_render_search_box\u0028\u0029",
            "name": "smartdocs_render_search_box",
            "summary": "Renders\u0020SmartDocs\u0020search\u0020form.",
            "url": "namespaces/default.html#function_smartdocs_render_search_box"
        },                {
            "fqsen": "\\smartdocs_render_categories\u0028\u0029",
            "name": "smartdocs_render_categories",
            "summary": "Renders\u0020a\u0020grid\u0020of\u0020SmartDocs\u0020categories.",
            "url": "namespaces/default.html#function_smartdocs_render_categories"
        },                {
            "fqsen": "\\smartdocs_header\u0028\u0029",
            "name": "smartdocs_header",
            "summary": "Hero\u0020section.",
            "url": "namespaces/default.html#function_smartdocs_header"
        },                {
            "fqsen": "\\smartdocs_hero_title\u0028\u0029",
            "name": "smartdocs_hero_title",
            "summary": "Hero\u0020title.",
            "url": "namespaces/default.html#function_smartdocs_hero_title"
        },                {
            "fqsen": "\\smartdocs_hero_description\u0028\u0029",
            "name": "smartdocs_hero_description",
            "summary": "Hero\u0020description.",
            "url": "namespaces/default.html#function_smartdocs_hero_description"
        },                {
            "fqsen": "\\smartdocs_search_form\u0028\u0029",
            "name": "smartdocs_search_form",
            "summary": "Output\u0020Search\u0020form\u0020using\u0020shortcode.",
            "url": "namespaces/default.html#function_smartdocs_search_form"
        },                {
            "fqsen": "\\smartdocs_output_content_wrapper_start\u0028\u0029",
            "name": "smartdocs_output_content_wrapper_start",
            "summary": "Content\u0020wrappers\u0020start.",
            "url": "namespaces/default.html#function_smartdocs_output_content_wrapper_start"
        },                {
            "fqsen": "\\smartdocs_output_content_wrapper_end\u0028\u0029",
            "name": "smartdocs_output_content_wrapper_end",
            "summary": "Content\u0020wrappers\u0020end.",
            "url": "namespaces/default.html#function_smartdocs_output_content_wrapper_end"
        },                {
            "fqsen": "\\smartdocs_archive_content\u0028\u0029",
            "name": "smartdocs_archive_content",
            "summary": "Archive\u0020page\u0020content.",
            "url": "namespaces/default.html#function_smartdocs_archive_content"
        },                {
            "fqsen": "\\smartdocs_get_sidebar\u0028\u0029",
            "name": "smartdocs_get_sidebar",
            "summary": "Get\u0020sidebar\u0020for\u0020single\u0020doc\u0020and\u0020category\u0020pages.",
            "url": "namespaces/default.html#function_smartdocs_get_sidebar"
        },                {
            "fqsen": "\\smartdocs_output_content_area_wrapper_start\u0028\u0029",
            "name": "smartdocs_output_content_area_wrapper_start",
            "summary": "Content\u0020area\u0020wrappers\u0020start.",
            "url": "namespaces/default.html#function_smartdocs_output_content_area_wrapper_start"
        },                {
            "fqsen": "\\smartdocs_output_content_area_wrapper_end\u0028\u0029",
            "name": "smartdocs_output_content_area_wrapper_end",
            "summary": "Content\u0020area\u0020wrappers\u0020end.",
            "url": "namespaces/default.html#function_smartdocs_output_content_area_wrapper_end"
        },                {
            "fqsen": "\\smartdocs_entry_header\u0028\u0029",
            "name": "smartdocs_entry_header",
            "summary": "Single\u0020doc\u0020entry\u0020header.",
            "url": "namespaces/default.html#function_smartdocs_entry_header"
        },                {
            "fqsen": "\\smartdocs_entry_footer\u0028\u0029",
            "name": "smartdocs_entry_footer",
            "summary": "Single\u0020doc\u0020entry\u0020footer.",
            "url": "namespaces/default.html#function_smartdocs_entry_footer"
        },                {
            "fqsen": "\\smartdocs_entry_content\u0028\u0029",
            "name": "smartdocs_entry_content",
            "summary": "Single\u0020doc\u0020entry\u0020content.",
            "url": "namespaces/default.html#function_smartdocs_entry_content"
        },                {
            "fqsen": "\\smartdocs_entry_meta\u0028\u0029",
            "name": "smartdocs_entry_meta",
            "summary": "Single\u0020doc\u0020entry\u0020meta.",
            "url": "namespaces/default.html#function_smartdocs_entry_meta"
        },                {
            "fqsen": "\\smartdocs_doc_actions\u0028\u0029",
            "name": "smartdocs_doc_actions",
            "summary": "Single\u0020doc\u0020actions.",
            "url": "namespaces/default.html#function_smartdocs_doc_actions"
        },                {
            "fqsen": "\\smartdocs_doc_feedback\u0028\u0029",
            "name": "smartdocs_doc_feedback",
            "summary": "Single\u0020doc\u0020feedback\u0020\u002D\u0020upvotes\/downvotes.",
            "url": "namespaces/default.html#function_smartdocs_doc_feedback"
        },                {
            "fqsen": "\\smartdocs_categorized_articles\u0028\u0029",
            "name": "smartdocs_categorized_articles",
            "summary": "Show\u0020articles\u0020on\u0020category\u0020archive.",
            "url": "namespaces/default.html#function_smartdocs_categorized_articles"
        },                {
            "fqsen": "\\smartdocs_category_title\u0028\u0029",
            "name": "smartdocs_category_title",
            "summary": "Category\u0020archive\u0020title.",
            "url": "namespaces/default.html#function_smartdocs_category_title"
        },                {
            "fqsen": "\\smartdocs_breadcrumb\u0028\u0029",
            "name": "smartdocs_breadcrumb",
            "summary": "Output\u0020the\u0020SmartDocs\u0020Breadcrumb.",
            "url": "namespaces/default.html#function_smartdocs_breadcrumb"
        },                {
            "fqsen": "\\smartdocs_get_template_part\u0028\u0029",
            "name": "smartdocs_get_template_part",
            "summary": "Get\u0020template\u0020part\u0020\u0028for\u0020templates\u0020like\u0020the\u0020archive,\u0020single\u0029.",
            "url": "namespaces/default.html#function_smartdocs_get_template_part"
        },                {
            "fqsen": "\\smartdocs_get_template\u0028\u0029",
            "name": "smartdocs_get_template",
            "summary": "Get\u0020other\u0020templates\u0020\u0028e.g.\u0020header,\u0020search\u0020form,\u0020etc.\u0029\u0020passing\u0020attributes\u0020and\u0020including\u0020the\u0020file.",
            "url": "namespaces/default.html#function_smartdocs_get_template"
        },                {
            "fqsen": "\\_smartdocs_get_doc_terms\u0028\u0029",
            "name": "_smartdocs_get_doc_terms",
            "summary": "Cached\u0020version\u0020of\u0020wp_get_post_terms\u0028\u0029.",
            "url": "namespaces/default.html#function__smartdocs_get_doc_terms"
        },                {
            "fqsen": "\\is_smartdocs_archive\u0028\u0029",
            "name": "is_smartdocs_archive",
            "summary": "See\u0020if\u0020current\u0020page\u0020is\u0020SmartDocs\u0020post\u0020type\u0020archive\u0020or\u0020not.",
            "url": "namespaces/default.html#function_is_smartdocs_archive"
        },                {
            "fqsen": "\\is_smartdocs_single\u0028\u0029",
            "name": "is_smartdocs_single",
            "summary": "See\u0020if\u0020current\u0020page\u0020is\u0020SmartDocs\u0020post\u0020type\u0020single\u0020or\u0020not.",
            "url": "namespaces/default.html#function_is_smartdocs_single"
        },                {
            "fqsen": "\\is_smartdocs_category\u0028\u0029",
            "name": "is_smartdocs_category",
            "summary": "See\u0020if\u0020current\u0020page\u0020is\u0020SmartDocs\u0020taxonomy\u0020or\u0020not.",
            "url": "namespaces/default.html#function_is_smartdocs_category"
        },                {
            "fqsen": "\\smartdocs_get_current_terms\u0028\u0029",
            "name": "smartdocs_get_current_terms",
            "summary": "Get\u0020current\u0020post\u0020terms\u0020or\u0020current\u0020term\u0027s\u0020parent.",
            "url": "namespaces/default.html#function_smartdocs_get_current_terms"
        },                {
            "fqsen": "\\smartdocs_post_class\u0028\u0029",
            "name": "smartdocs_post_class",
            "summary": "Post\u0020class\u0020for\u0020docs.",
            "url": "namespaces/default.html#function_smartdocs_post_class"
        },                {
            "fqsen": "\\smartdocs_get_docs_page_link\u0028\u0029",
            "name": "smartdocs_get_docs_page_link",
            "summary": "Get\u0020docs\u0020page\u0020link\u0020based\u0020on\u0020SmartDocs\u0020template\u0020setting.",
            "url": "namespaces/default.html#function_smartdocs_get_docs_page_link"
        },                {
            "fqsen": "\\smartdocs_get_support_page_link\u0028\u0029",
            "name": "smartdocs_get_support_page_link",
            "summary": "Get\u0020support\u0020page\u0020link\u0020from\u0020SmartDocs\u0020setting.",
            "url": "namespaces/default.html#function_smartdocs_get_support_page_link"
        },                {
            "fqsen": "\\smartdocs_get_category_thumbnail_url\u0028\u0029",
            "name": "smartdocs_get_category_thumbnail_url",
            "summary": "Get\u0020category\u0020thumbnail\u0020URL.",
            "url": "namespaces/default.html#function_smartdocs_get_category_thumbnail_url"
        },                {
            "fqsen": "\\smartdocs_list_docs\u0028\u0029",
            "name": "smartdocs_list_docs",
            "summary": "Fetch\u0020and\u0020list\u0020the\u0020articles\u0020from\u0020the\u0020given\u0020term.",
            "url": "namespaces/default.html#function_smartdocs_list_docs"
        },                {
            "fqsen": "\\smartdocs_list_categories\u0028\u0029",
            "name": "smartdocs_list_categories",
            "summary": "Fetch\u0020and\u0020list\u0020the\u0020categories\u0020in\u0020hierarchy.",
            "url": "namespaces/default.html#function_smartdocs_list_categories"
        },                {
            "fqsen": "\\FlattedString",
            "name": "FlattedString",
            "summary": "",
            "url": "classes/FlattedString.html"
        },                {
            "fqsen": "\\FlattedString\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/FlattedString.html#method___construct"
        },                {
            "fqsen": "\\Flatted",
            "name": "Flatted",
            "summary": "",
            "url": "classes/Flatted.html"
        },                {
            "fqsen": "\\Flatted\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Flatted.html#method_parse"
        },                {
            "fqsen": "\\Flatted\u003A\u003Astringify\u0028\u0029",
            "name": "stringify",
            "summary": "",
            "url": "classes/Flatted.html#method_stringify"
        },                {
            "fqsen": "\\Flatted\u003A\u003AasString\u0028\u0029",
            "name": "asString",
            "summary": "",
            "url": "classes/Flatted.html#method_asString"
        },                {
            "fqsen": "\\Flatted\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/Flatted.html#method_index"
        },                {
            "fqsen": "\\Flatted\u003A\u003Akeys\u0028\u0029",
            "name": "keys",
            "summary": "",
            "url": "classes/Flatted.html#method_keys"
        },                {
            "fqsen": "\\Flatted\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "",
            "url": "classes/Flatted.html#method_loop"
        },                {
            "fqsen": "\\Flatted\u003A\u003Arelate\u0028\u0029",
            "name": "relate",
            "summary": "",
            "url": "classes/Flatted.html#method_relate"
        },                {
            "fqsen": "\\Flatted\u003A\u003Aref\u0028\u0029",
            "name": "ref",
            "summary": "",
            "url": "classes/Flatted.html#method_ref"
        },                {
            "fqsen": "\\Flatted\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "",
            "url": "classes/Flatted.html#method_transform"
        },                {
            "fqsen": "\\Flatted\u003A\u003Awrap\u0028\u0029",
            "name": "wrap",
            "summary": "",
            "url": "classes/Flatted.html#method_wrap"
        },                {
            "fqsen": "\\console",
            "name": "console",
            "summary": "",
            "url": "classes/console.html"
        },                {
            "fqsen": "\\console\u003A\u003Aassert\u0028\u0029",
            "name": "assert",
            "summary": "",
            "url": "classes/console.html#method_assert"
        },                {
            "fqsen": "\\SmartDocs\\notice_php_version\u0028\u0029",
            "name": "notice_php_version",
            "summary": "Shows\u0020Admin\u0020Notice\u0020for\u0020PHP\u0020compatibility.",
            "url": "namespaces/smartdocs.html#function_notice_php_version"
        },                {
            "fqsen": "\\SmartDocs\\notice_wp_version\u0028\u0029",
            "name": "notice_wp_version",
            "summary": "Shows\u0020admin\u0020notice\u0020for\u0020minimum\u0020WordPress\u0020version.",
            "url": "namespaces/smartdocs.html#function_notice_wp_version"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SmartDocs",
            "name": "SmartDocs",
            "summary": "",
            "url": "namespaces/smartdocs.html"
        },                {
            "fqsen": "\\SmartDocs\\Widgets",
            "name": "Widgets",
            "summary": "",
            "url": "namespaces/smartdocs-widgets.html"
        }            ]
);
